El3yada/El3yada/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("MainMenu.urls")),
    path('login/',include("login.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

El3yada/MainMenu/urls.py
from django.urls import path,include,register_converter
from rest_framework import routers
from . import views
from datetime import datetime,date
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'appointments', views.AppointmentViewSet,basename='appointmentsAPI')
router.register(r'patients', views.PatientViewSet,basename='patientsAPI')
router.register(r'services', views.ServiceViewSet,basename='servicesAPI')
router.register(r'payments', views.PaymentsViewSet,basename='paymentsAPI')
router.register(r'today',views.AppointmentDayViewSet,basename='dayviewAPI')

class DateConverter:
      regex = r"\d{4}-\d{1,2}-\d{1,2}"
      format = "%Y-%m-%d"

      def to_python(self, value: str) -> date:
          return datetime.strptime(value, self.format).date()

      def to_url(self, value: date) -> str:
          return value.strftime(self.format)

register_converter(DateConverter, "date")

print(date)

urlpatterns=[
    path("api/",include(router.urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/addnewapp/', views.AddNewAppointmentView.as_view(), name='addnewapp'),
    path('api/getapppay/', views.GetAppointmentToPayForView.as_view(), name='getapppay'),
    path("api/addnewpat/",views.AddNewPatientView.as_view(),name="addnewpat"),
    path('api/editapp/<int:Aser>', views.EditAppointmentView.as_view(), name='editapp'),
    path('api/paydiag/<int:Aser>', views.PayDiagnosisAppointmentView.as_view(), name='paydiag'),
    path('api/payserv/<int:Aser>', views.PayServiceAppointmentView.as_view(), name='payserv'),
    path('api/editpat/<int:Ser>', views.EditPatientView.as_view(), name='editpat'),
    path('api/add_debts/<int:Ser>/<int:Aser>', views.AddDebtsView.as_view(), name='add_debts'),
    path('api/doctors/', views.DoctorView.as_view(), name='doctors'),
    path("",views.index,name='index'),
    path("adduser/",views.AddUsers,name="addusers"),
    path("addappointment/<int:Ser>",views.appointmentadd,name="addappointments"),
    path("patient/create/",views.PatientAdd,name="patientadd"),
    path("patient/<int:Ser>",views.PatientView,name="patientview"),
    path('appointment/<int:Aser>',views.AppointmentView,name='updateappointment'),
    path('payment/<int:Pser>',views.payment,name='payment'),
    path('appointment/<date:Adate>',views.viewday,name='viewdayappointment'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/count/<str:category>/<int:rowsper>', views.count,name='countview')
]

El3yada/login/urls.py
from re import template
from django.urls import path
from . import views
from django.contrib.auth import views as authviews

urlpatterns=[
    path("",authviews.LoginView.as_view(template_name="login.html"),name="login"),
    path("logout/",authviews.LogoutView.as_view(template_name="logout.html"),name="logout")
]

El3yada/MainMenu/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator
from datetime import date
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError


class Services(models.Model):
    name= models.CharField(_("Service Name"), max_length=50)
    price = models.IntegerField(_("Service Price"),validators=[MinValueValidator(0)])
    cost = models.IntegerField(_("Service Cost"),validators=[MinValueValidator(0)])
    description = models.TextField(_("Description"),null=True,blank=True)
    def __str__(self):
        return "{0} ({1} L.E.)".format(self.name,self.price)

class Doctor(models.Model):
    name = models.CharField(_("Doctor Name"),max_length=50)
    services = models.ManyToManyField(Services, verbose_name=_("Services"))
    def __str__(self):
        return "{0} , {1}".format(self.name,self.services.name)



class appointments(models.Model):
    Aser = models.IntegerField(unique=True,null=True)
    Pser = models.IntegerField(null=True,blank=True)
    Aname = models.TextField(null=True,blank=True)
    Aphone = models.TextField(null=True,blank=True)
    Atel = models.TextField(null=True,blank=True)
    Adate = models.DateField(null=True,blank=True)
    ServNo = models.IntegerField(null=True,blank=True)
    Arem = models.TextField(null=True,blank=True)
    Arraive = models.BooleanField(null=True,blank=True,default=False)
    DocNo = models.IntegerField(null=True,blank=True)
    admin = User.objects.first().username
    DocName = models.TextField(null=True,blank=True,default='دكتورة منال ابو الفضل')
    Fees = models.IntegerField(null=True,blank=True)
    Cost = models.IntegerField(null=True,blank=True)
    Paid = models.IntegerField(null=True,blank=True)
    ShouldPay = models.BooleanField(null=True,blank=True,default=True)
    Seen = models.BooleanField(null=True,blank=True)
    DoneBy = models.TextField(null=True,blank=True,default=admin)
    Per = models.IntegerField(null=True,blank=True)
    AMPMCode = models.TextField(null=True,blank=True)
    AMPM = models.TextField(null=True,blank=True)
    ContrC = models.IntegerField(null=True,blank=True)
    MoneyBy = models.TextField(null=True,blank=True,default=admin)
    MoneyNo = models.IntegerField(null=True,blank=True)
    def __str__(self):
        return "{0}, {1}, ({2}), {3}, Fees: {4}".format(self.Aser,self.Pser,self.Aname,self.Adate,self.Fees)

class patient(models.Model):
    Ser = models.IntegerField(unique=True,null=True)
    PName = models.TextField(null=True,blank=True)
    PatNote = models.TextField(null=True,blank=True)
    BirthDate = models.DateField(null=True,blank=True)
    
    Sex = models.TextField(null=True,blank=True,default='ذكر')
    Job = models.TextField(null=True,blank=True)
    Mstatus = models.TextField(null=True,blank=True)
    Street = models.TextField(null=True,blank=True)
    Phone = models.TextField(null=True,blank=True)
    Mobile = models.TextField(null=True,blank=True)
    Admission = models.DateField(null=True,blank=True)
    ContC = models.IntegerField(null=True,blank=True)
    ContN = models.TextField(null=True,blank=True)
    Ref = models.TextField(null=True,blank=True)
    Co = models.TextField(null=True,blank=True)
    Pro = models.TextField(null=True,blank=True)
    DELT = models.BooleanField(null=True,blank=True)
    Debts = models.IntegerField(null=True,blank=True)
    def __str__(self):
        return "{0},{1},{2},{3}".format(self.Ser,self.PName,self.Mobile,self.Street)

class Payments(models.Model):
    Appointment = models.ForeignKey(appointments,on_delete=models.PROTECT)
    Paid_Amount = models.IntegerField(validators=[MinValueValidator(1)])
    Date = models.DateField(default=date.today)
    MoneyBy = models.TextField(null=True,blank=True)
    def __str__(self):
        return 'payment for appointment (({0})) on {1} with {2} L.E by {3}'.format(self.Appointment,self.Date,self.Paid_Amount,self.MoneyBy)

class Resource(models.Model):
    ResourceType = [
            ("UTIL"  , "Utility Bills"),
            ("NET"   , "Internet Bill"),
            ("TEL"   , "Telephone Bill"),
            ("FDWTR" , "Food / Water Resupply"),
            ("TXC"   , "Toxic Wastes"),
            ("MRKT"  , "Marketing"),
            ("CNSM"  , "Consumables"),
            ("MOB"   , "Mobile Phone Bills"),
            ("NC"    , "Not Categorized")
        ]
    Type = models.CharField(
        _("Type of Resource"),
        max_length=5,
        choices=ResourceType,
        default=ResourceType[-1],
    )
    Name = models.CharField(_("Resource Name"),max_length=200)
    Counter = models.CharField(_("Counter"),max_length=50, default='items')
    def __str__(self):
        return '{0} of type "{1}" which is sold by {2}'.format(self.Name,self.Type,self.Counter)
    
class Supplier(models.Model):
    Name = models.TextField(_("Supplier Name"))
    def __str__(self):
        return self.Name

class Expense(models.Model):
    Supplier = models.ForeignKey(Supplier,verbose_name="Supplier",on_delete=models.PROTECT)
    ItemPaidFor = models.ForeignKey(Resource,verbose_name='Resource bought',on_delete=models.PROTECT)
    AmountOfItem = models.DecimalField(_("Amount"),decimal_places=2,max_digits=20)
    Price = models.DecimalField(_("Price of Resource"),max_digits=50,decimal_places=2,null=True)
    AmountPaid = models.DecimalField(_("Paid"),max_digits=50,decimal_places=2)
    Date = models.DateField()
    ReceiptID = models.CharField(_("ID of Receipt"), max_length=100,unique=True)    
    
    def __str__(self):
        return 'On {0}, A sum of money, which equals {1} L.E. only, was paid to {2} for {3} {4} of {5}'.format(self.Date,self.AmountPaid,self.Supplier,self.AmountOfItem,self.ItemPaidFor.Counter,self.ItemPaidFor.Name)

El3yada/MainMenu/forms.py
from django.forms import ModelForm, Textarea
from django.db.models import F,Q
from django.utils.translation import gettext_lazy as _
from .models import appointments, patient,Payments

class PatientForm(ModelForm):
    # specify the name of model to use
    def __init__(self, *args, **kwargs):
       super(PatientForm, self).__init__(*args, **kwargs)
       self.fields['Debts'].widget.attrs['readonly'] = True
    class Meta:
        model = patient
        exclude = ['id','Pro','Co','DELT','ContC','ContN','Ref']
        widgets = {
            'Mobile': Textarea(attrs={'cols': 80, 'rows': 1}),
            'PName': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Job': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Mstatus': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Street': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Phone': Textarea(attrs={'cols': 80, 'rows': 1}),
            'ContN': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Ref': Textarea(attrs={'cols': 80, 'rows': 1}),

        }
        labels={
            'PName': _('Patient Name'),
            'Ser': _('Patient Number'),
            'BirthDate':_('Date Of Birth'),
            'Mstatus':_('Marital Status'),
            'PatNote':_("Patient Notes")
        }

class AppointmentForm(ModelForm):
    # specify the name of model to use
    def __init__(self, *args, **kwargs):
       super(AppointmentForm, self).__init__(*args, **kwargs)
       self.fields['Fees'].widget.attrs['readonly'] = True
       self.fields['Pser'].widget.attrs['readonly'] = True
    class Meta:
        model = appointments
        exclude = ['id','AMPM','AMPMCode','Seen','ServNo','DocNo','MoneyNo','ContrC','Cost']
        widgets = {
            'Aser': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Pser': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Adate': Textarea(attrs={'cols': 80, 'rows': 1}),
            # 'Arem': Textarea(attrs={'cols': 80, 'rows': 1}),
            # 'DocName': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Fees': Textarea(attrs={'cols': 80, 'rows': 1}),

        }
        labels={
            'Aser': _('Appointment Number'),
            'Pser': _('Patient Number'),
            'Adate':_('Date'),
            'Arem':_('Service'),
            'DocName':_("Doctor's Name")
        }

class FrontEndAppointment(AppointmentForm):
    class Meta(AppointmentForm.Meta):
        model = appointments
        exclude = ['id','AMPM','AMPMCode','Seen','ServNo','Aname','Aphone','Atel','Paid','Cost','DocNo','MoneyNo','ContrC','Per']

class UpdatePatientForm(ModelForm):
    # specify the name of model to use
    def __init__(self, *args, **kwargs):
       super(UpdatePatientForm, self).__init__(*args, **kwargs)
       self.fields['Debts'].widget.attrs['readonly'] = True
    class Meta:
        model = patient
        exclude = ['id','Pro','Co','DELT','Ser','ContC','ContN','Ref']
        widgets = {
            'Mobile': Textarea(attrs={'cols': 80, 'rows': 1}),
            'PName': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Job': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Mstatus': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Street': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Phone': Textarea(attrs={'cols': 80, 'rows': 1}),
            'ContN': Textarea(attrs={'cols': 80, 'rows': 1}),
            'Ref': Textarea(attrs={'cols': 80, 'rows': 1}),

        }
        labels={
            'PName': _('Patient Name'),
            'BirthDate':_('Date Of Birth'),
            'Mstatus':_('Marital Status'),
            'PatNote':_("Patient Notes")
        }
        
class UpdateExtraInfo(ModelForm):
    class Meta:
        model = appointments
        fields = ['Aname','Atel','Aphone']

class PaymentForm(ModelForm):
    def __init__(self,Pser,*args,**kwargs):
            super (PaymentForm,self ).__init__(*args,**kwargs) # populates the post
            self.fields['Appointment'].queryset = appointments.objects.filter(Pser=Pser).filter(Q(Paid__lt=F('Fees')) | Q(Paid__isnull=True) & Q(ShouldPay=True))
    class Meta:
        model= Payments
        fields=['Appointment','Paid_Amount','Date']
        

El3yada/MainMenu/templates/MainMenu/AddUsers.html
{%extends 'layout.html' %}
{% load static %}
{%load crispy_forms_tags%}
{%block content%}
      <h1 class="text-center">Welcome, {{user.first_name}} {{user.last_name}}</h1>
      {%if messages%}
            <div class="container">
                  {%for message in messages%}
                        {%if message.tags == "warning"%}
                        <div class="alert alert-{{message.tags}} text-center blink-bg" >{{message}}</div>
                        {%else%}
                        <div class="alert alert-{{message.tags}} text-center" >{{message}}</div>
                        {%endif%}
                  {%endfor%}
            </div>
            {%endif%}
      <!-- Registration -->
      <div class="container content-section">
            <form method="post">
                  {%csrf_token%}
                  <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Add Users</legend>
                        {{form|crispy}}
                  </fieldset>
                  <div class="text-center">
                        <input type="submit" class="btn btn-primary" value="Add User">
                  </div>
            </form>
      </div>
{%endblock%}

El3yada/MainMenu/templates/MainMenu/AppointmentAdd.html
{%extends 'layout.html' %}
{% load static %}
{%load crispy_forms_tags%}
{%block content%}
      
      <h1 class="text-center">Welcome, {{user.first_name}} {{user.last_name}}</h1>
      {%if messages%}
            <div class="container">
                  {%for message in messages%}
                        {%if message.tags == "warning"%}
                        <div class="alert alert-{{message.tags}} text-center blink-bg" >{{message}}</div>
                        {%else%}
                        <div class="alert alert-{{message.tags}} text-center" >{{message}}</div>
                        {%endif%}
                  {%endfor%}
            </div>
            {%endif%}
      
      <!-- Registration -->
      <div class="container content-section mb-5">
            <form method="post">
                  {%csrf_token%}
                  <fieldset class="form-group mb-5">
                        <legend class="border-bottom mb-4">Add Appointments</legend>
                        {{form|crispy}}
                  </fieldset>
                  <div class="text-center mb-5">
                        <input type="submit" class="btn btn-primary mb-5" value="Add Appointment">
                  </div>
            </form>
      </div>
      <script type="text/javascript">
            Object.prototype.in = function() {
                  for(var i=0; i<arguments.length; i++)
                     if(arguments[i] == this) return true;
                  return false;
            }
            let globaldata; 
            function getOption(){
                  selectElement1 = document.querySelector('#id_DocName').value;
                  if (selectElement1 != ''){
                  URL = "http://127.0.0.1:8000/api/doctors/?doctor=" + selectElement1 + '&format=json';
                  console.log(URL);
                  fetch(URL, {
                        method: 'GET',
                        headers:{
                              'Accept': 'application/json',
                              'X-Requested-With': 'XMLHttpRequest', //Necessary to work with request.is_ajax()
                        },
                  })
                  .then(response => response.json())
                  .then(data => {
                        console.log('Success:', data);
                        console.log('Success:', data[0]['services']);
                        URL = "http://127.0.0.1:8000/api/services/?service=" + data[0]['services'] + '&format=json';
                        console.log(URL)
                        fetch(URL, {
                              method: 'GET',
                              headers:{
                                    'Accept': 'application/json',
                                    'X-Requested-With': 'XMLHttpRequest', //Necessary to work with request.is_ajax()
                              },
                        })
                        .then(response=> response.json())
                        .then(data=>{
                              console.log('Success:', data);
                              const brands = data.map(({ name }) => name);
                              console.log(brands);
                              selectElement2 = document.querySelector('#id_Arem');
                              selectElement2.value='';
                              for(let i = 1;i<selectElement2.length;i++){
                                    selectElement2.children[i].style.display= 'block';
                                    if (!brands.includes(selectElement2.children[i].value))
                                    {
                                          console.log(selectElement2.children[i].value);
                                          selectElement2.children[i].style.display= 'none';
                                    }
                              }
                              globaldata = data;
                              getFees();
                        })
                        .catch(error => {
                              console.error('Error:', error);
                        });
                  })
                  .catch(error => {
                        console.error('Error:', error);
                  });
                  
            }
          }
          function getFees(){
            selectElement1 = document.getElementById("id_Fees");
            selectElement2 = document.getElementById("id_Arem");
            const names = globaldata.map(({ name }) => name);
            const fees = globaldata.map(({ price }) => price);
            console.log(selectElement2.value);
            console.log(selectElement1.value);
            console.log(names);
            console.log(fees);
            if (selectElement2.value != '' && names.includes(selectElement2.value))
            {
                  let index = names.indexOf(selectElement2.value);
                  console.log(index);
                  console.log(fees[index]);
                  selectElement1.value = fees[index];
            }
            else if (selectElement2.value === '')
            {
                  selectElement1.value = '';
            }
      }
          function docReady(fn) {
            // see if DOM is already available
            if (document.readyState === "complete" || document.readyState === "interactive") {
                // call on next available tick
                setTimeout(fn, 1);
            } else {
                document.addEventListener("DOMContentLoaded", fn);
            }
        }    
        docReady(function() {
            getOption();
            document.getElementById("id_DocName").addEventListener("change", getOption);
            document.getElementById("id_Arem").addEventListener("change", getFees);
        });
      
        </script>
{%endblock%}

El3yada/MainMenu/templates/MainMenu/AppointmentView.html
{%extends 'layout.html' %}
{% load static %}
{%load crispy_forms_tags%}
{%block content%}
      <h1 class="text-center">Welcome, {{user.first_name}} {{user.last_name}}</h1>
      <div class="container">
        {%if messages%}
            <div class="container">
                  {%for message in messages%}
                        {%if message.tags == "warning"%}
                        <div class="alert alert-{{message.tags}} text-center blink-bg" >{{message}}</div>
                        {%else%}
                        <div class="alert alert-{{message.tags}} text-center" >{{message}}</div>
                        {%endif%}
                  {%endfor%}
            </div>
            {%endif%}
      </div>
      <div class="container content-section mb-5">
            <div class="container-fluid table-responsive mt-3 mb-5 text-nowrap">
                <table class="table table-bordered caption-top mb-5">
                    <tr>
                        {%for x in columns%}
                        <th>{{x}}</th>
                        {%endfor%}
                    </tr>
                    <tr>
                    {%for item in list%}
                        {%if item is None%}
                            <td></td>
                        {%else%}
                                <td>{{item}}</td>
                        {%endif%}
                    {%endfor%}
                    </tr>
                </table>
            </div>
            <form method="post" action="">
                {%csrf_token%}
                {{uform|crispy}}
                <div class="text-center">
                <input type="submit" class="btn btn-primary my-5" name='update' value="Update">
                </div>
            </form>
      </div>
      
{%endblock%}

El3yada/MainMenu/templates/MainMenu/PatientAdd.html
{%extends 'layout.html' %}
{% load static %}
{%load crispy_forms_tags%}
{%block content%}
      <h1 class="text-center">Welcome, {{user.first_name}} {{user.last_name}}</h1>
      {%if messages%}
            <div class="container">
                  {%for message in messages%}
                        {%if message.tags == "warning"%}
                        <div class="alert alert-{{message.tags}} text-center blink-bg" >{{message}}</div>
                        {%else%}
                        <div class="alert alert-{{message.tags}} text-center" >{{message}}</div>
                        {%endif%}
                  {%endfor%}
            </div>
            {%endif%}
      <!-- Registration -->
      <div class="container content-section mb-5">
            <form method="post">
                  {%csrf_token%}
                  <fieldset class="form-group mb-5">
                        <legend class="border-bottom mb-4">Add Patients</legend>
                        {{form|crispy}}
                  </fieldset>
                  <div class="text-center mb-5">
                        <input type="submit" class="btn btn-primary mb-5" value="Add Patient">
                  </div>
            </form>
      </div>
{%endblock%}

El3yada/MainMenu/templates/MainMenu/PatientInfo.html
{%extends 'layout.html' %}
{%load crispy_forms_tags%}
{%block content%}
      <h1 class="text-center">Welcome, {{user.first_name}} {{user.last_name}}</h1>
      <!-- Registration -->
      <div class="container content-section mb-5">
            <form method="post">
                  {%csrf_token%}
                  <fieldset class="form-group mb-5">
                        <legend class="border-bottom mb-4">Add Patients</legend>
                        {{form|crispy}}
                  </fieldset>
                  <div class="text-center mb-5">
                        <input type="submit" class="btn btn-primary mb-5" value="Add Patient">
                  </div>
            </form>
      </div>
{%endblock%}

El3yada/MainMenu/templates/MainMenu/PatientView.html
{%extends 'layout.html' %}
{% load static %}
{% load mathfilters %}
{%load crispy_forms_tags%}
{%block content%}
      <h1 class="text-center">Welcome, {{user.first_name}} {{user.last_name}}</h1>
        {%if messages%}
            <div class="container">
                  {%for message in messages%}
                        {%if message.tags == "warning"%}
                        <div class="alert alert-{{message.tags}} text-center blink-bg" >{{message}}</div>
                        {%else%}
                        <div class="alert alert-{{message.tags}} text-center" >{{message}}</div>
                        {%endif%}
                  {%endfor%}
            </div>
            {%endif%}
      <div class="container content-section mb-5">
            <p>
                
                {%for item1,item2 in Plist%}
                    {%if item1 == "Patient Notes" and patnotes != '' and patnotes > 0%}
                    <div class="alert alert-danger text-center blink-bg" ><strong>{{patnotes}} L.E Remaining</strong></div>
                    {%endif%}
                    {%if item1 != "Patient Notes"%}
                    {{item1}} : {{item2}}<br>
                    {%elif item2 != None and item2 != ''%}
                    <div class="alert alert-danger text-center blink-bg" ><strong>{{item2}}</strong></div>
                    {%endif%}
                {%endfor%}
            </p>
            <div class="text-center my-3">
                <a href="/addappointment/{{Ser}}">
                    <input type="submit" class="btn btn-primary mx-3" value="Add Appointment">
                </a>
            </div>
            <div class="text-center my-3">
                <a href="/payment/{{Ser}}">
                    <input type="submit" class="btn btn-primary mx-3" value="Add Payment">
                </a>
            </div>
            <div class="container-fluid table-responsive mt-3 mb-5 text-nowrap">
                  
                
                <table class="table table-sm table-bordered caption-top mb-5">
                    <tr>
                        {%for x in columns%}
                        <th>{{x}}</th>
                        {%endfor%}
                    </tr>
                    {%if lists%}
                        {%for list in lists%}
                            {%if list.11|sub:list.13 > 0%}
                            <tr class='blink-bg'>
                            {%else%}
                            <tr>
                            {%endif%}
                            {%for item in list%}
                                {%if item is None%}
                                    <td></td>
                                {%else%}
                                        <td>{{item}}</td>
                                {%endif%}
                            {%endfor%}
                            </tr>
                        {%endfor%}
                    {%endif%}
                </table>
            </div>
            <div class="container-fluid table-responsive mt-3 mb-5 text-nowrap">
                <table class="table table-sm table-bordered caption-top mb-5">
                    <tr>
                        {%for x in columnspayment%}
                        <th>{{x}}</th>
                        {%endfor%}
                    </tr>
                    {%if Paylists%}
                        {%for list in Paylists%}
                            <tr>
                            {%for item in list%}
                                {%if item is None%}
                                    <td></td>
                                {%else%}
                                        <td>{{item}}</td>
                                {%endif%}
                            {%endfor%}
                            </tr>
                        {%endfor%}
                    {%endif%}
                </table>
            </div>
            <form method="post" action="">
                {%csrf_token%}
                {{uform|crispy}}
                {{hform.as_hidden}}
                <div class="text-center">
                <input type="submit" class="btn btn-primary my-5" name='update' value="Update">
                </div>
            </form>
      </div>
      
{%endblock%}

El3yada/MainMenu/templates/MainMenu/ViewDay.html
{%extends 'layout.html' %}
{% load static %}
{%load crispy_forms_tags%}
{%block content%}
      {%if user.first_name%}
      <h1 class="text-center my-5">Welcome, {{user.first_name}} {{user.last_name}}</h1>
      {%else%}
      <h1 class="text-center my-5">Welcome, {{user.username}}</h1>
      {%endif%}
      <div class="container">
            {%if messages%}
            <div class="container">
                  {%for message in messages%}
                        {%if message.tags == "warning"%}
                        <div class="alert alert-{{message.tags}} text-center blink-bg" >{{message}}</div>
                        {%else%}
                        <div class="alert alert-{{message.tags}} text-center" >{{message}}</div>
                        {%endif%}
                  {%endfor%}
            </div>
            {%endif%}
      </div>
      <div id="react" class="container-fluid table-responsive mt-3 mb-5 text-nowrap">
            <table class="table table-sm table-bordered caption-top mb-5">
                <caption>List of Appointments Today</caption>
                  <tr>
                        {%for x in columns%}
                        <th>{{x}}</th>
                        {%endfor%}
                  </tr>
            {%if lists%}
                  {%for list in lists%}
                        <tr>
                        {%for item in list%}
                              {%if forloop.counter0 == 8%}
                              <td>
                                    <form method="post" id="myform{{forloop.parentloop.counter0}}">
                                          {%csrf_token%}
                                          <input type="hidden" name="name" value="{{list.0}}"> 
                                          <a onclick="document.getElementById('myform{{forloop.parentloop.counter0}}').submit();" href="#" >{{item}}</a>
                                    </form>
                              </td>
                              {%else%}
                              <td>{{item}}</td>
                              {%endif%}
                        {%endfor%}
                        </tr>
                  {%endfor%}
            {%endif%}
      </div>
{%endblock%}